### ISSUE TITLE
Failed to start the Hello World test

### ISSUE THREAD

**Issue by Murii** [non-dev/nide#1] opened 2015-01-28 10:26 UTC
This is what I get on Ubuntu 14.04 running on 64 bits: 

Exception in thread "Thread-6" java.lang.Error: Interrupted attempt to aquire write lock
	at javax.swing.text.AbstractDocument.writeLock(AbstractDocument.java:1349)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:702)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.JTextArea.append(JTextArea.java:477)
	at nide.Console.print(Console.java:34)
	at nide.Console.run(Console.java:77)
	at java.lang.Thread.run(Thread.java:745)

And this I get into the Nide`s console : 
Executing '/home/murii/Desktop/IDE/non.jar desktop:run'
> Checking for latest version DONE
> Checking dependencies and updating data DONE
> Executing 'gradlew desktop:run' FAILED
Configuration on demand is an incubating feature.
:update
:
Task finished with non-zero result

**Comment by deathbeam** [comment] 2015-01-28 12:04
Nide is still heavy WIP and your error is probably caused by inrerrupting not running thread. I am going to switch to daemon threads in next update. Also, this should be issue with not using EventQueue.invokeLater when printing messages.Try to replace this in Console.java:
public void print(String msg) {
        append(msg);
        setCaretPosition(getDocument().getLength());
}

with this:
public void print(String msg) {
        EventQueue.invokeLater(new Runnable() {
			public void run () {
                                    append(msg);
                                    setCaretPosition(getDocument().getLength());
                        }
        }
}
EventQueue.invokeLater(new Runnable() {
			public void run () {
				ui.textArea.append("" + c);
				ui.textArea.setCaretPosition(ui.textArea.getDocument().getLength());
			}

**Comment by deathbeam** [comment] 2015-01-30 09:04
Closing, fixed with latest commit 3bf28d6dee54df0ee1f9dcd16adb52f5796c7cab

**Closed by deathbeam** 2015-01-30 09:04 UTC
